pring.application.name=movie-db

# H2 Datasource
spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=p4ssw0rd!


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
